language: php
sudo: required
dist: trusty

php:
  - 5.6

install:
  - phpenv config-rm xdebug.ini
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - composer global require drupal/coder
  - phpcs --config-set installed_paths ~/.config/composer/vendor/drupal/coder/coder_sniffer

before_script:
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script: ./travis.sh

notifications:
  email:
    - anap@ciandt.com

